[tool.poetry]
name = "test-task"
version = "0.1.0"
description = ""
authors = ["ivan <ivanbelousov14@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
selenium = "^4.25.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
